"""create initial tripweaver schema

Revision ID: 1e49fcba08a7
Revises:
Create Date: 2026-08-17 19:03:45.153941

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e49fcba08a7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trips",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column("requester_email", sa.String(length=320), nullable=True),
        sa.Column("origin_iata", sa.String(length=3), nullable=False),
        sa.Column("destination_iata", sa.String(length=3), nullable=False),
        sa.Column("depart_date", sa.Date(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column("adults", sa.Integer(), nullable=False),
        sa.Column("max_budget_usd", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "researching",
                "planning",
                "awaiting_approval",
                "approved",
                "booked",
                "cancelled",
                "failed",
                name="trip_status",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    )
    op.create_index(
        "ix_trips_origin_destination", "trips", ["origin_iata", "destination_iata"], unique=False
    )
    op.create_index("ix_trips_requester_email", "trips", ["requester_email"], unique=False)
    op.create_index("ix_trips_status", "trips", ["status"], unique=False)
    op.create_table(
        "flight_options",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "trip_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_offer_id", sa.String(length=255), nullable=False),
        sa.Column("total_price_usd", sa.Float(), nullable=False),
        sa.Column("cabin_class", sa.String(length=30), nullable=False),
        sa.Column("stops_outbound", sa.Integer(), nullable=False),
        sa.Column(
            "segments",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_flight_options_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_options")),
    )
    op.create_index("ix_flight_options_selected", "flight_options", ["is_selected"], unique=False)
    op.create_index(
        "ix_flight_options_trip_price",
        "flight_options",
        ["trip_id", "total_price_usd"],
        unique=False,
    )
    op.create_table(
        "hotel_options",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "trip_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_offer_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("total_price_usd", sa.Float(), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("star_rating", sa.Float(), nullable=True),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_hotel_options_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel_options")),
    )
    op.create_index("ix_hotel_options_selected", "hotel_options", ["is_selected"], unique=False)
    op.create_index(
        "ix_hotel_options_trip_price", "hotel_options", ["trip_id", "total_price_usd"], unique=False
    )
    op.create_table(
        "itineraries",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "trip_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("day_date", sa.Date(), nullable=False),
        sa.Column(
            "plan",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_itineraries_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itineraries")),
    )
    op.create_index(
        "ix_itineraries_trip_day", "itineraries", ["trip_id", "day_number"], unique=True
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "trip_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("booking_type", sa.Enum("flight", "hotel", name="booking_type"), nullable=False),
        sa.Column(
            "flight_option_id",
            sa.UUID().with_variant(sa.String(length=36), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "hotel_option_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_approval",
                "approved",
                "rejected",
                "booked",
                "booking_failed",
                "cancelled",
                name="booking_status",
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("total_price_usd", sa.Float(), nullable=False),
        sa.Column("provider_booking_reference", sa.String(length=255), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flight_option_id"],
            ["flight_options.id"],
            name=op.f("fk_bookings_flight_option_id_flight_options"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hotel_option_id"],
            ["hotel_options.id"],
            name=op.f("fk_bookings_hotel_option_id_hotel_options"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_bookings_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("idempotency_key", name="uq_bookings_idempotency_key"),
    )
    op.create_index("ix_bookings_status", "bookings", ["status"], unique=False)
    op.create_index("ix_bookings_trip_id", "bookings", ["trip_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "booking_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column(
            "decision",
            sa.Enum("pending", "approved", "rejected", name="approval_decision"),
            nullable=False,
        ),
        sa.Column("decided_by", sa.String(length=320), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("decision_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_approvals_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("booking_id", name="uq_approvals_booking_id"),
    )
    op.create_index("ix_approvals_decision", "approvals", ["decision"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column("trip_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=True),
        sa.Column(
            "booking_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=True
        ),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_audit_log_booking_id_bookings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_audit_log_trip_id_trips"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_booking_id", "audit_log", ["booking_id"], unique=False)
    op.create_index("ix_audit_log_event_type", "audit_log", ["event_type"], unique=False)
    op.create_index("ix_audit_log_trip_id", "audit_log", ["trip_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_log_trip_id", table_name="audit_log")
    op.drop_index("ix_audit_log_event_type", table_name="audit_log")
    op.drop_index("ix_audit_log_booking_id", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_approvals_decision", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_bookings_trip_id", table_name="bookings")
    op.drop_index("ix_bookings_status", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_itineraries_trip_day", table_name="itineraries")
    op.drop_table("itineraries")
    op.drop_index("ix_hotel_options_trip_price", table_name="hotel_options")
    op.drop_index("ix_hotel_options_selected", table_name="hotel_options")
    op.drop_table("hotel_options")
    op.drop_index("ix_flight_options_trip_price", table_name="flight_options")
    op.drop_index("ix_flight_options_selected", table_name="flight_options")
    op.drop_table("flight_options")
    op.drop_index("ix_trips_status", table_name="trips")
    op.drop_index("ix_trips_requester_email", table_name="trips")
    op.drop_index("ix_trips_origin_destination", table_name="trips")
    op.drop_table("trips")
    # ### end Alembic commands ###
