"""Add car rental schema

Revision ID: 4bedf8413dbb
Revises: 1e49fcba08a7
Create Date: 2026-08-22 21:43:44.482345

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bedf8413dbb"
down_revision: str | Sequence[str] | None = "1e49fcba08a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "car_rental_options",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_rate_id", sa.String(length=255), nullable=False),
        sa.Column("provider_quote_id", sa.String(length=255), nullable=True),
        sa.Column("car_description", sa.String(length=255), nullable=False),
        sa.Column("supplier_name", sa.String(length=255), nullable=False),
        sa.Column("payment_type", sa.String(length=20), nullable=False),
        sa.Column("total_price_usd", sa.Float(), nullable=False),
        sa.Column("pickup_location_name", sa.String(length=255), nullable=False),
        sa.Column("dropoff_location_name", sa.String(length=255), nullable=False),
        sa.Column("pickup_at", sa.DateTime(), nullable=False),
        sa.Column("dropoff_at", sa.DateTime(), nullable=False),
        sa.Column(
            "driver_details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_car_rental_options_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_car_rental_options")),
    )
    op.create_index(
        "ix_car_rental_options_selected", "car_rental_options", ["is_selected"], unique=False
    )
    op.create_index(
        "ix_car_rental_options_trip_price",
        "car_rental_options",
        ["trip_id", "total_price_usd"],
        unique=False,
    )
    op.add_column("bookings", sa.Column("car_rental_option_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_bookings_car_rental_option_id_car_rental_options"),
        "bookings",
        "car_rental_options",
        ["car_rental_option_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_bookings_car_rental_option_id_car_rental_options"), "bookings", type_="foreignkey"
    )
    op.drop_column("bookings", "car_rental_option_id")
    op.drop_index("ix_car_rental_options_trip_price", table_name="car_rental_options")
    op.drop_index("ix_car_rental_options_selected", table_name="car_rental_options")
    op.drop_table("car_rental_options")
    # ### end Alembic commands ###
