"""add audit_log sequence column with per-trip uniqueness

Revision ID: 5fd9b6369c1e
Revises: 7cfb6a64b2eb
Create Date: 2026-09-01 08:59:36.830356

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fd9b6369c1e"
down_revision: str | Sequence[str] | None = "7cfb6a64b2eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable first -- existing audit_log rows (written by
    # propose_booking(), which already uses this table) predate this
    # column and need backfilling before NOT NULL can be enforced.
    op.add_column("audit_log", sa.Column("sequence", sa.BigInteger(), nullable=True))
    # One-time backfill for historical rows, using their existing
    # created_at order (fine for this one-time correction -- created_at's
    # coarse resolution is only a problem for NEW rows written close
    # together in time, which log_stage_event() now avoids by computing
    # sequence itself; see that function's docstring). id is a secondary
    # ORDER BY key purely to make ties deterministic, not chronologically
    # meaningful.
    op.execute("""
        WITH ranked AS (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY trip_id ORDER BY created_at, id
            ) AS rn
            FROM audit_log
        )
        UPDATE audit_log
        SET sequence = ranked.rn
        FROM ranked
        WHERE audit_log.id = ranked.id
    """)
    op.alter_column("audit_log", "sequence", nullable=False)
    op.create_unique_constraint(
        "uq_audit_log_trip_id_sequence", "audit_log", ["trip_id", "sequence"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_audit_log_trip_id_sequence", "audit_log", type_="unique")
    op.drop_column("audit_log", "sequence")
    # ### end Alembic commands ###
