"""add wants_car_rental to trips

Revision ID: c90802ddf121
Revises: 5fd9b6369c1e
Create Date: 2026-09-01 19:06:36.611182

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c90802ddf121"
down_revision: str | Sequence[str] | None = "5fd9b6369c1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default=false, not just nullable=True + backfill -- every
    # pre-existing trip genuinely never requested a car rental via this
    # field (it didn't exist yet), so false is both the constraint-
    # satisfying value AND the semantically correct one for historical
    # rows, unlike audit_log.sequence's per-row backfill.
    op.add_column(
        "trips",
        sa.Column("wants_car_rental", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Drop the server_default after backfilling existing rows -- new rows
    # should always get their value explicitly from create_trip(), not
    # silently default to false if a caller forgets to pass it.
    op.alter_column("trips", "wants_car_rental", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "wants_car_rental")
    # ### end Alembic commands ###
